// <auto-generated />
using System;
using InvoiceDesigner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceDesigner.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260708125648_AddProductCodeToInvoiceItem")]
    partial class AddProductCodeToInvoiceItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceDesigner.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizedPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MersisNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxOffice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("InvoiceDesigner.Models.FieldDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FieldDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Müşteri Bilgileri",
                            DataType = "text",
                            DisplayName = "Müşteri Adı",
                            FieldKey = "Customer.CompanyName",
                            Source = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Müşteri Bilgileri",
                            DataType = "text",
                            DisplayName = "Adres",
                            FieldKey = "Customer.Address",
                            Source = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Müşteri Bilgileri",
                            DataType = "text",
                            DisplayName = "Vergi Dairesi",
                            FieldKey = "Customer.TaxOffice",
                            Source = "Customer"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Müşteri Bilgileri",
                            DataType = "text",
                            DisplayName = "Vergi No",
                            FieldKey = "Customer.TaxNumber",
                            Source = "Customer"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Müşteri Bilgileri",
                            DataType = "text",
                            DisplayName = "Mersis No",
                            FieldKey = "Customer.MersisNo",
                            Source = "Customer"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Fatura Bilgileri",
                            DataType = "text",
                            DisplayName = "Fatura No",
                            FieldKey = "Invoice.InvoiceNo",
                            Source = "Invoice"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Fatura Bilgileri",
                            DataType = "date",
                            DisplayName = "Fatura Tarihi",
                            FieldKey = "Invoice.InvoiceDate",
                            Source = "Invoice"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Fatura Bilgileri",
                            DataType = "decimal",
                            DisplayName = "Ara Toplam",
                            FieldKey = "Invoice.SubTotal",
                            Source = "Invoice"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Fatura Bilgileri",
                            DataType = "decimal",
                            DisplayName = "KDV Tutarı",
                            FieldKey = "Invoice.TaxAmount",
                            Source = "Invoice"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Fatura Bilgileri",
                            DataType = "decimal",
                            DisplayName = "Genel Toplam",
                            FieldKey = "Invoice.TotalAmount",
                            Source = "Invoice"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Ürün Bilgileri",
                            DataType = "text",
                            DisplayName = "Ürün/Hizmet Adı",
                            FieldKey = "Item.ProductName",
                            Source = "InvoiceItem"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Ürün Bilgileri",
                            DataType = "decimal",
                            DisplayName = "Adet",
                            FieldKey = "Item.Quantity",
                            Source = "InvoiceItem"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Ürün Bilgileri",
                            DataType = "decimal",
                            DisplayName = "Birim Fiyat",
                            FieldKey = "Item.UnitPrice",
                            Source = "InvoiceItem"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Ürün Bilgileri",
                            DataType = "decimal",
                            DisplayName = "KDV Oranı",
                            FieldKey = "Item.VatRate",
                            Source = "InvoiceItem"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Ürün Bilgileri",
                            DataType = "decimal",
                            DisplayName = "Satır Toplamı",
                            FieldKey = "Item.LineTotal",
                            Source = "InvoiceItem"
                        });
                });

            modelBuilder.Entity("InvoiceDesigner.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("InvoiceDesigner.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("InvoiceDesigner.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviewImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("InvoiceDesigner.Models.Invoice", b =>
                {
                    b.HasOne("InvoiceDesigner.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceDesigner.Models.Template", "Template")
                        .WithMany("Invoices")
                        .HasForeignKey("TemplateId");

                    b.Navigation("Customer");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("InvoiceDesigner.Models.InvoiceItem", b =>
                {
                    b.HasOne("InvoiceDesigner.Models.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceDesigner.Models.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("InvoiceDesigner.Models.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InvoiceDesigner.Models.Template", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
